[package]
name = "oasis"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path="src/main.rs"
name = "oasis"

[dependencies]
actix-web = "4.3.1"
config = "0.10"
reqwest = "0.11.22"
serde = "1.0.193"
shuttle-actix-web = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
uuid = {version="1.6.1", features=["v4"]}
chrono = "0.4.31"
