# configuration.yaml
application: 
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres_user"
  password: "password"
  database_name: "oasis"
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"